### ISSUE TITLE
The whole code is an issue. rm -rf / and fix

### ISSUE THREAD

**Issue by T3hArco** [Fedict/eid-viewer#1]
Please

**Comment by T3hArco** [comment]
https://github.com/Fedict/eid-viewer/blob/master/eid-viewer-gui/src/main/java/be/fedict/eidviewer/gui/BelgianEidViewer.java

**Comment by yoe** [comment]
This isn't a bug report. If you have a specific problem, feel free to contact the Fedict service desk for assistance. If you can point to a particular issue in the code, feel free to point to it in more detail.

In the absense of that, closing this issue.
