### ISSUE TITLE
*moderated* Java error message

### ISSUE THREAD

**Issue by rhythmus** [Fedict/eid-viewer#2]
<img width="532" alt="schermafbeelding 2016-07-04 om 23 16 06" src="https://cloud.githubusercontent.com/assets/903152/16570176/eb5380a8-4240-11e6-9388-9a55214455ab.png">

**Comment by Frederikus** [comment]
The current eID Viewer is Java based indeed.
We are working on a new eID Viewer, which will be native.

**Comment by FeitianSmartcardReader** [comment]
@Frederikus  are you planing develop iOS version? that alllow user check their eID card information on mobile. For example, it should be useful when user want apply SIM card or something can check their identify their information.

**Comment by Frederikus** [comment]
We have no short term plans to develop an iOS version of the eID Viewer, nor for the eID Middleware.
You can however authenticate on government sites using iOS (https://idp.iamfas.belgium.be/fasui/login/totpservice). This has been developed by another team however.
