### ISSUE TITLE
eID Viewer drag and drop encoding error

### ISSUE THREAD

**Issue by greg7110** [Fedict/eid-viewer#3]
When I use the "drag and drop" (picture) feature of eID Viewer to a web page (example in eid-iewer/xml/) I have encoding errors like:
- é = Ã©
- è = Ã¨

It's work fine when I use the "save as xml" feature and I drag the xml files on web page

**Comment by yoe** [comment]
I can't seem to be able to reproduce this with the browsers I've tried.

Which browser are you using? On which operating system?

**Comment by greg7110** [comment]
I'm on Winwdows 8 64 bits, Chrome 53.0.2785.116 m and Internet Explorer 11.0.9600.18450.

I try to "drag and drop" directly in Edit Plus and the result is the same.

**Comment by yoe** [comment]
This looks like it's a problem with Unicode encoding on Windows defaulting to utf-16 rather than utf-8. The issue will be solved with the native viewer we are developing and which is nearing completion, and will be somewhat complex to fix in the Java viewer.

**Comment by greg7110** [comment]
Ok, thanks for your answer.

Can you give me an approximate release date of the native viewer?

**Comment by yoe** [comment]
That's not been decided yet, but it should be reasonably soon.

**Comment by Hipska** [comment]
Do you have a date now? Because soon means nothing.

**Comment by yoe** [comment]
This issue should no longer exist with the native viewer, which has (finally) been released now.

Sorry for the long time it took us to get here.
