### ISSUE TITLE
Is it possible to make the eID viewer get focus upon inserting a card?

### ISSUE THREAD

**Issue by Wannes123** [Fedict/eid-viewer#5]
Hi,

Excuse me in advance if this is not the appropriate place for a question/suggestion.

Is it possible to make the eID viewer get focus (pop up to front) upon inserting a card?

This would be very useful when reading a lot of cards as part of a daily routine.

Thanks for considering,
Wannes Schols

**Comment by yoe** [comment]
Please reopen this in the right place: the Fedict/eid-mw project, as per the other bug ;-)

Thanks,

**Comment by Frederikus** [comment]
Hey Wannes,

Thanks for the suggestion, we'll keep it in mind for future versions.
Feel free to re-post your suggestion in the other project, like Wouter suggested, that way you can keep track of it.
