### ISSUE TITLE
[Error] C_OpenSession(slot, 0x00000004, 0, 0, &session) returned 0xe1

### ISSUE THREAD

**Issue by mesqueeb** [Fedict/eid-viewer#7]
I have the following errors in the eID viewer:
```
D: Handling state transition for event TOKEN_INSERTED
D: Leaving state READY
D: Leaving state NO_TOKEN
D: Entering state TOKEN (target)
D: C_OpenSession(slot, 0x00000004, 0, 0, &session) returned 0xe1
D: Entering state TOKEN_ID (child)
D: C_FindObjectsInit(session, &attr, 1) returned 0xb3
D: Handling state transition for event STATE_ERROR
D: Leaving state TOKEN_ID
D: C_FindObjectsFinal(session) returned 0xb3
D: Entering state TOKEN_ERROR (target)
D: State transition for STATE_ERROR complete
D: State transition detected, aborting handling of TOKEN_INSERTED
```

I'm using the following card reader:
Opluz Smart Card Reader OPM691
http://www.opluz.net/en/productshow.asp?id=127

What are the indications I need to look out for if I want to check if my card reader is compatible?
Since I live in Japan it's difficult to find electronics they sell only in Belgium...

**Comment by yoe** [comment]
If you live in Japan, am I correct in guessing that your card was issued by the consulate or embassy there?

If that is indeed the case, then that is your problem, not the card reader. Consulates and embassies do not have the necessary infrastructure to activate your card, which means they are issued in their inactive state. Cards cannot be read by the eid software until they are activated.

If not, feel free to reopen this issue.

**Comment by mesqueeb** [comment]
@yoe Thank you so much for the advice Wouter.
I'll contact my embassy to ask the possibilities for me how to get my card activated!

Have a good day!
