### ISSUE TITLE
dnd functionality 

### ISSUE THREAD

**Issue by ghost** [Fedict/eid-viewer#8]
Hello there,

`// Did the user drop a file, or drag data out of the eID-Viewer?
		// NOTE: the necessary changes to the eID-Viewer to
		// support this (without saving a file and dropping that
		// out of a file manager) have not yet been released,
		// and won't be until after tax-on-web.`

[dnd.html](https://github.com/Fedict/eid-viewer/blob/master/xml/dnd.html)

Latest version doesn't seems to have this functionality yet.

Any chance it'll be implemented in the near future?

Thanks 👍

**Comment by Frederikus** [comment]
see https://github.com/Fedict/eid-mw/issues/84)
